import { Paragraph, HeadingLevel, TextRun, AlignmentType, Table, TableRow, TableCell, WidthType, BorderStyle } from "docx";
import type { ReportInput } from "../types";

export function buildCoverPage(input: ReportInput) {
    const { assetInfo } = input;

    const metadataTable = new Table({
        width: { size: 90, type: WidthType.PERCENTAGE },
        rows: [
            metaRow("Client Name", assetInfo.clientName),
            metaRow("Asset ID / Tag", assetInfo.assetTag),
            metaRow("Inspection Date", assetInfo.inspectionDate),
            metaRow("Operator Name", assetInfo.operatorName),
            metaRow("Inspection Method", assetInfo.method),
            metaRow("Report ID", assetInfo.reportId),
        ],
        columnWidths: [30, 70],
    });

  return [
    new Paragraph({
      text: "Corrosion Inspection Report",
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 800 },
    }),
    new Paragraph({
        text: "Generated by Sigma Corrosion Detective",
        alignment: AlignmentType.CENTER,
        spacing: { after: 1200 },
    }),
    metadataTable,
  ];
}


function metaRow(label: string, value: string) {
    return new TableRow({
        children: [
            new TableCell({
                children: [new Paragraph({ children: [new TextRun({ text: label, bold: true })]})],
                borders: {
                    top: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
                    bottom: { style: BorderStyle.SINGLE, size: 1, color: "D3D3D3" },
                    left: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
                    right: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
                },
                shading: { fill: "F8F8F8" },
            }),
            new TableCell({
                children: [new Paragraph(value)],
                 borders: {
                    top: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
                    bottom: { style: BorderStyle.SINGLE, size: 1, color: "D3D3D3" },
                    left: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
                    right: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
                },
            }),
        ]
    });
}
