import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Augment jsPDF with the autoTable plugin
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

const loadBase64Image = (url: string): Promise<string | null> => {
    return new Promise((resolve) => {
        const img = new Image();
        img.crossOrigin = 'Anonymous'; 
        img.src = url;
        img.onload = () => {
            const canvas = document.createElement('canvas');
            canvas.width = img.width;
            canvas.height = img.height;
            const ctx = canvas.getContext('2d');
            if (ctx) {
                ctx.drawImage(img, 0, 0);
                resolve(canvas.toDataURL('image/png'));
            } else {
                resolve(null);
            }
        };
        img.onerror = () => {
            console.warn("Logo failed to load");
            resolve(null); 
        };
    });
};

export async function generateFinalReport(metadata: any, patches: any[]) {
    const doc = new jsPDF('p', 'mm', 'a4'); 
    const w = 210;
    const h = 297;
    
    const primaryColor: [number, number, number] = [0, 51, 102]; 
    const accentColor: [number, number, number] = [230, 240, 255]; 

    const logoUrl = "/logo.png"; 
    const logoData = await loadBase64Image(logoUrl);

    const addPageStyling = () => {
        doc.setDrawColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        doc.setLineWidth(0.5);
        doc.rect(5, 5, w - 10, h - 10); 
    };

    // --- PAGE 1: TITLE & SUMMARY ---
    addPageStyling();

    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(5, 5, w - 10, 40, 'F'); 
    
    if (logoData) {
        doc.addImage(logoData, 'PNG', 10, 10, 50, 20); 
    }
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("INSPECTION REPORT", w - 15, 20, { align: 'right' });
    doc.setFontSize(10);
    doc.text("Generated by Sigma Corrosion Detective", w - 15, 30, { align: 'right' });

    let y = 60;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    
    const drawMetaRow = (label: string, value: string) => {
        doc.setFont("helvetica", "bold");
        doc.text(label, 20, y);
        doc.setFont("helvetica", "normal");
        doc.text(":  " + value, 60, y);
        doc.setDrawColor(200, 200, 200);
        doc.line(20, y + 2, w - 20, y + 2); 
        y += 10;
    };

    drawMetaRow("Asset Name", metadata.assetName);
    drawMetaRow("Location", metadata.location);
    drawMetaRow("Date", metadata.inspectionDate);
    drawMetaRow("Inspector", metadata.inspector);

    y += 10;
    doc.setFillColor(accentColor[0], accentColor[1], accentColor[2]);
    doc.roundedRect(20, y, w - 40, 30, 3, 3, 'F');
    doc.setFont("helvetica", "bold");
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text("Executive Summary / Remarks:", 25, y + 8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text(doc.splitTextToSize(metadata.remarks, w - 50), 25, y + 16);
    
    y += 40;
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Inspection Summary Table", 20, y);
    y += 8;

    const tableData = patches.map(p => [
        p.id,
        `X: ${p.xMin.toFixed(0)}-${p.xMax.toFixed(0)}\nY: ${p.yMin.toFixed(0)}-${p.yMax.toFixed(0)}`,
        p.inspected ? `${p.minThickness.toFixed(2)} mm` : 'N/A',
        p.inspected ? `${p.maxCorrosion.toFixed(1)}%` : 'N/A',
        p.inspected ? 'Inspected' : 'NOT INSPECTED'
    ]);
    
    doc.autoTable({
        startY: y,
        head: [['Section', 'Area (mm)', 'Min Thickness', 'Max Corrosion', 'Status']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: primaryColor },
        styles: { cellPadding: 2, fontSize: 9 },
        columnStyles: {
            4: { cellWidth: 30 }
        }
    });

    // --- PATCH PAGES ---
    patches.forEach((patch) => {
        if (!patch.inspected) return;

        doc.addPage();
        addPageStyling();

        doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        doc.rect(5, 5, w - 10, 15, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text(`SECTION ${patch.id} - DETAIL`, 10, 14);

        let sectionY = 25;
        doc.setFontSize(10);
        doc.setTextColor(0,0,0);
        doc.text(`Area: X ${patch.xMin.toFixed(0)} - ${patch.xMax.toFixed(0)} mm, Y ${patch.yMin.toFixed(0)} - ${patch.yMax.toFixed(0)} mm`, 10, sectionY);
        sectionY += 7;
        doc.text(`Findings: Min Thickness: ${patch.minThickness.toFixed(2)} mm, Max Corrosion: ${patch.maxCorrosion.toFixed(1)}%`, 10, sectionY);
        sectionY += 10;
        
        const imgSize = 92;
        const gap = 6;
        const startX = 10;

        const label = (text: string, x: number, y: number) => {
            doc.setFillColor(0, 0, 0, 0.5);
            doc.rect(x, y, 25, 5, 'F');
            doc.setTextColor(255, 255, 255);
            doc.setFontSize(8);
            doc.text(text, x + 2, y + 3.5);
        };
        
        if (patch.views.iso) {
            doc.addImage(patch.views.iso, 'PNG', startX, sectionY, imgSize, imgSize);
            label("ISO VIEW", startX, sectionY);
        }
        if (patch.views.top) {
            doc.addImage(patch.views.top, 'PNG', startX + imgSize + gap, sectionY, imgSize, imgSize);
            label("TOP VIEW", startX + imgSize + gap, sectionY);
        }
    });

    doc.save(`${metadata.assetName}_Section_Report.pdf`);
}
