
import jsPDF from 'jspdf';

// 1. ROBUST IMAGE LOADER (Fixes missing logo issues)
const loadBase64Image = (url: string): Promise<string | null> => {
    return new Promise((resolve) => {
        const img = new Image();
        img.crossOrigin = 'Anonymous'; 
        img.src = url;
        img.onload = () => {
            const canvas = document.createElement('canvas');
            canvas.width = img.width;
            canvas.height = img.height;
            const ctx = canvas.getContext('2d');
            if (ctx) {
                ctx.drawImage(img, 0, 0);
                resolve(canvas.toDataURL('image/png'));
            } else {
                resolve(null);
            }
        };
        img.onerror = () => {
            console.warn("Logo failed to load");
            resolve(null); 
        };
    });
};

export async function generateFinalReport(metadata: any, patches: any[]) {
    const doc = new jsPDF('p', 'mm', 'a4'); 
    const w = 210;
    const h = 297;
    
    // Theme Colors
    const primaryColor: [number, number, number] = [0, 51, 102]; 
    const accentColor: [number, number, number] = [230, 240, 255]; 

    // Load Logo 
    const logoUrl = "/logo.png"; 
    const logoData = await loadBase64Image(logoUrl);

    // HELPER: Add Page Border & Watermark
    const addPageStyling = () => {
        // Border
        doc.setDrawColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        doc.setLineWidth(0.5);
        doc.rect(5, 5, w - 10, h - 10); 

        // Watermark
        doc.saveGraphicsState();
        doc.setTextColor(230, 230, 230);
        doc.setFontSize(60);
        doc.setFont("helvetica", "bold");
        doc.text("SIGMA NDT", 40, h - 50, { angle: 45 });
        doc.restoreGraphicsState();
    };

    // --- PAGE 1: TITLE & SUMMARY ---
    addPageStyling();

    // Header
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(5, 5, w - 10, 40, 'F'); 
    
    if (logoData) {
        doc.addImage(logoData, 'PNG', 10, 10, 50, 20); 
    }
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("INSPECTION REPORT", w - 15, 20, { align: 'right' });
    doc.setFontSize(10);
    doc.text("Generated by Sigma Corrosion Detective", w - 15, 30, { align: 'right' });

    // Metadata Table
    let y = 60;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    
    const drawMetaRow = (label: string, value: string) => {
        doc.setFont("helvetica", "bold");
        doc.text(label, 20, y);
        doc.setFont("helvetica", "normal");
        doc.text(":  " + value, 60, y);
        doc.setDrawColor(200, 200, 200);
        doc.line(20, y + 2, w - 20, y + 2); 
        y += 10;
    };

    drawMetaRow("Asset Name", metadata.assetName);
    drawMetaRow("Location", metadata.location);
    drawMetaRow("Date", metadata.inspectionDate);
    drawMetaRow("Inspector", metadata.inspector);

    // Remarks
    y += 10;
    doc.setFillColor(accentColor[0], accentColor[1], accentColor[2]);
    doc.roundedRect(20, y, w - 40, 30, 3, 3, 'F');
    doc.setFont("helvetica", "bold");
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text("Executive Summary / Remarks:", 25, y + 8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text(doc.splitTextToSize(metadata.remarks, w - 50), 25, y + 16);

    // --- PATCH PAGES ---
    patches.forEach((patch) => {
        doc.addPage();
        addPageStyling();

        // Ribbon Header
        doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        doc.rect(5, 5, w - 10, 20, 'F'); // Made it slightly taller
        
        // Title
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text(`PATCH ${patch.id} ANALYSIS`, 10, 14);
        
        // --- NEW: LOCATION DATA ---
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        const locText = `Location Center:  X: ${patch.location.x.toFixed(1)} mm   |   Y: ${patch.location.y.toFixed(1)} mm   |   Z: ${patch.location.z.toFixed(1)} mm`;
        doc.text(locText, 10, 22);

        // Severity Label (Right side)
        doc.setFont("helvetica", "bold");
        doc.text("SEVERITY: CRITICAL", w - 50, 15); 


        // 2x2 GRID
        const imgSize = 92;
        const gap = 6;
        const startY = 30; // Adjusted for taller header
        const startX = 10;

        const label = (text: string, x: number, y: number) => {
            doc.setFillColor(0, 0, 0);
            doc.rect(x, y - 5, 25, 5, 'F');
            doc.setTextColor(255, 255, 255);
            doc.setFontSize(8);
            doc.text(text, x + 2, y - 1);
        };

        // Row 1
        if (patch.views.top) {
            doc.addImage(patch.views.top, 'PNG', startX, startY, imgSize, imgSize);
            label("TOP VIEW", startX, startY);
        }
        if (patch.views.side) {
            doc.addImage(patch.views.side, 'PNG', startX + imgSize + gap, startY, imgSize, imgSize);
            label("SIDE VIEW", startX + imgSize + gap, startY);
        }

        // Row 2
        const row2Y = startY + imgSize + 5;
        if (patch.views.iso) {
            doc.addImage(patch.views.iso, 'PNG', startX, row2Y, imgSize, imgSize);
            label("ISO VIEW", startX, row2Y);
        }
        if (patch.views.map) {
            doc.addImage(patch.views.map, 'PNG', startX + imgSize + gap, row2Y, imgSize, imgSize);
            label("2D MAP", startX + imgSize + gap, row2Y);
        }

        // Footer
        const footerY = 230;
        doc.setDrawColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        doc.setLineWidth(0.5);
        doc.line(10, footerY, w - 10, footerY);
        doc.setFontSize(12);
        doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        doc.text("AI AUTOMATED INSIGHT", 10, footerY + 8);
        doc.setFontSize(9);
        doc.setTextColor(50, 50, 50);
        doc.text(`Analysis complete for Patch ${patch.id}. Please review areas with thickness deviation > 10%.`, 10, footerY + 15);
    });

    doc.save(`${metadata.assetName}_Final_Report.pdf`);
}
